services:
  app:
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.placeholder1.rule=Host(`donmacaron.net`)
      - traefik.http.routers.placeholder1.entrypoints=webs
      - traefik.http.routers.placeholder1.tls.certresolver=myresolver
      - traefik.http.routers.placeholder2.rule=Host(`donmacaron.net`)
      - traefik.http.routers.placeholder2.entrypoints=web
      - traefik.http.routers.placeholder2.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.port=443
      - traefik.http.services.placeholder.loadbalancer.server.port=8000
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
